import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: '#0049B7',
          50: '#E6F0FF',
          100: '#CCE1FF',
          200: '#99C3FF',
          300: '#66A5FF',
          400: '#3387FF',
          500: '#0049B7',
          600: '#003A94',
          700: '#002B70',
          800: '#001C4D',
          900: '#000D29',
          950: '#000419',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: '#FF1D58',
          50: '#FFE6ED',
          100: '#FFCCDB',
          200: '#FF99B7',
          300: '#FF6693',
          400: '#FF336F',
          500: '#FF1D58',
          600: '#E6004A',
          700: '#B30039',
          800: '#800028',
          900: '#4D0017',
          foreground: 'hsl(var(--accent-foreground))',
        },
        accent2: {
          DEFAULT: '#F75990',
          50: '#FEE6EF',
          100: '#FDCCE0',
          200: '#FB99C1',
          300: '#F966A2',
          400: '#F75990',
          500: '#F5336B',
          600: '#E6005A',
          700: '#B30046',
          800: '#800032',
          900: '#4D001E',
        },
        warn: {
          DEFAULT: '#FFF685',
          50: '#FFFEF5',
          100: '#FFFDE0',
          200: '#FFFBC2',
          300: '#FFF9A3',
          400: '#FFF785',
          500: '#FFF685',
          600: '#E6DD00',
          700: '#B3AB00',
          800: '#807A00',
          900: '#4D4800',
        },
        info: {
          DEFAULT: '#00DDFF',
          50: '#E6FAFF',
          100: '#CCF5FF',
          200: '#99EBFF',
          300: '#66E1FF',
          400: '#33D7FF',
          500: '#00DDFF',
          600: '#00B1CC',
          700: '#008599',
          800: '#005866',
          900: '#002C33',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
}
export default config