version: "3.9"
services:
  web:
    build: ./apps/web
    env_file: ./.env
    depends_on: [api]
    ports: ["3000:3000"]
  api:
    build: ./apps/api
    env_file: ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - INTERNAL_SERVICE_TOKEN=${INTERNAL_SERVICE_TOKEN}
      - REDIS_URL=${REDIS_URL}
    depends_on: [db]
    ports: ["8000:8000"]
  worker:
    build: ./workers/etl
    env_file: ./.env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    depends_on: [db, redis]
    command: ["celery", "-A", "tasks.celery_app", "worker", "-l", "INFO"]
  beat:
    build: ./workers/etl
    command: ["celery", "-A", "tasks.celery_app", "beat", "-l", "INFO"]
    env_file: ./.env
    depends_on: [worker]
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tip
    ports: ["5432:5432"]
  redis:
    image: redis:7
    ports: ["6379:6379"]